#!/bin/bash
set -x

action="$1"
cur_version="$2"


. /usr/share/debconf/confmodule 

db_input high openhim-console/selecthost || true

db_input high openhim-console/selectport || true


db_go || true
