#!/bin/bash
set -e

action="$1"
cur_version="$2"


. /usr/share/debconf/confmodule 

# reset database if reconfigure
if [ "$action" = "reconfigure" ]; then
    db_purge || true
fi


db_input high openhim-console/selecthost || true
db_input high openhim-console/selectport || true
db_go


