#!/bin/bash
set -e

CONSOLEDIR=/usr/share/nginx/html/openhim
CONFIGFILE=$CONSOLEDIR/config/default.json
ETCCONFIGFILE=/etc/openhim/console-config.json

. /usr/share/debconf/confmodule
db_get openhim-console/selecthost
HOST=$RET
db_get openhim-console/selectport
PORT=$RET

# Keep existing config file if there is one
mkdir /etc/openhim || true
if [ ! -f $ETCCONFIGFILE ]; then
    cp $CONFIGFILE $ETCCONFIGFILE
else
    echo "Existing config file found, using that."
fi

# Replace the config with a link to a config in /etc/openhim/
rm $CONFIGFILE
ln -s $ETCCONFIGFILE $CONFIGFILE

# Set host and port of openhim-core
cat $ETCCONFIGFILE | jq 'to_entries | map(if .key == "host" then . + {"value": "'$HOST'"} else . end) | from_entries' > /tmp/config.json && mv /tmp/config.json $ETCCONFIGFILE
cat $ETCCONFIGFILE | jq 'to_entries | map(if .key == "port" then . + {"value": "'$PORT'"} else . end) | from_entries' > /tmp/config.json && mv /tmp/config.json $ETCCONFIGFILE

echo "Successfully installed the OpenHIM-console!"

exit 0
