#!/bin/bash
set -x
set -e

USERNAME=openhim
HOME=/home/$USERNAME
SH=/bin/sh
NPM=/usr/bin/npm
CURL=/usr/bin/curl

CONSOLEDIR=$HOME/openhim-console


chown  $USERNAME:$USERNAME $HOME/bin/install_console.sh
chown -R  $USERNAME:$USERNAME $CONSOLEDIR

cd $HOME

. /usr/share/debconf/confmodule
db_get openhim-console/selecthost
HOST=$RET
db_get openhim-console/selectport
PORT=$RET

CONFIG="
{
  'protocol': 'https',
  'host': '$HOST',
  'port': $PORT,
  'title': 'OpenHIM Admin Console (Carl)',
  'footerTitle': 'OpenHIM Administration Console',
  'footerPoweredBy': '<a href="'"http://openhim.org/" target="_blank">Powered by OpenHIM</a>'"',
  'loginBanner': ''
}
"
echo $CONFIG > $CONSOLEDIR/app/config/default.json

exit 1
sudo -u $USERNAME $SH $HOME/bin/install_console.sh

start openhim-console

exit 0
